openapi: 3.0.0
info:
  version: 1.0.0
  title: Fuzzy Thesaurus API
  description: This API takes words and returns word synonyms, near synonyms, and insectional synonyms. It is intended to be the back end for threeshortwords.com.

servers:
  - url: http://www.threeshortwords.com

paths:
  /thesaurus:
    get:
      description: Returns a list of synonyms.
      parameters:
        - name: words
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
      responses: 
        '200':
          description: A JSON array of words.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string